### ISSUE TITLE
Question: How to reuse QueryHandler code?

### ISSUE THREAD

**Issue by fenilrathod** [JacobsDataSolutions/OrgManager#9]
First of all thanks for sharing blog posts and this code. I am using MediatR and Clean Architecture since last year in couple of projects and it is really helpful to have it.

However, I am not yet settle on how to reuse query-handler code in command-handler? Specifically when you are retrieving data from multiple entities and caching it into query handler.

Right now I am using services down line command handlers (like controller > (queries/commands) > services > entities). Services are responsible for cache. While notification events are used to invalidate the cache.

However, this way every query-handler logic starts going into services.

What is your view on reusing query-handler code and caching? 

Thanks in advance.

**Comment by JacobsDataSolutions** [comment]
One of the best experts I've found on this topic is Vladimir Khorikov. If you have access to Pluralsight, then I highly recommend his course, CQRS in Practice - https://app.pluralsight.com/library/courses/cqrs-in-practice

Under the module "CQRS Best Practices and Misconceptions" of the above mentioned course, subsection "Using Commands and Queries from Handlers" he perfectly echoes my own sentiment (see below):

Should you call Commands from Queries?

Short answer: NO.

Complex answer:
- Call a Command from another Command? - NO
- Call a Query from a Command? - Only if you are trying to implement Event Sourcing.
- Call a Command from a Query? - NO
- Call a Query from another Query? - ?????????

So building off of what he says, my answer to your question is that if you want to stay out of trouble, don't ever call a Command from a Query, _or vice versa_. Just don't do it. Even if your databases are in the same availability group and are mirror images of each other, don't do it. Even if you are only using one database, don't do it.

Now, your answer involves the topic of caching, which is important. It seems like you are trying to leverage Queries which get cached, etc. Please keep in mind that caching is ALWAYS an optimization in software theoretical terms, and that optimizations typically come with costs. Inside the logic in your CQRS Commands I would avoid accessing cached data (though I don't know your specific use case, so take what I say with a grain of salt). However, where Khorikov and I seem to be in agreement is that CQRS Commands should not access the Query (Read) database--they should get everything they need from the Command (Write) database. Even if you have to make a few queries before persisting whatever entities you need to, those queries should be going against the Command (Write) database. I talk about this in some detail in one of my previous blog entries--https://blog.jacobsdata.com/2020/09/25/scaffold-your-clean-ddd-web-application-part-3-persistence-tenancy-and-the-data-model

Where we are also in agreement is if you need to reuse queries in this regard, then they should go into services. Just make sure that you're querying the Command (Write) database. Clear as mud?

Thanks for your thoughtful question!

Happy coding,
J

**Comment by fenilrathod** [comment]
Thanks for course suggestion and the answer. It make sense. 
I am trying to access caching data in command as it mostly lookup or master data which needed for some kind of calculations. You are right cache is indeed costly and hard to implement.

Thanks Again.
FR

**Comment by JacobsDataSolutions** [comment]
It sounds like what you're doing is OK. If you have global data like master lookup lists then I think it's fine to use something like IDistributedCache to avoid making another trip to the database inside a Command. It also seems like you are encapsulating this inside services, which is the way to go. As long as you have a way to invalidate the cache and are OK managing the slightly added complexity then rock on. Where you would get into trouble is if you start caching core domain entities, the kinds of things that get returned from your main CQRS Queries. For example, in this demo application I would not allow any Command to access a cached list of employees, because that data will be changing not infrequently. However, a list of currencies? Totally fine. Good luck and thanks again!
